### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace', chapter 2

### ISSUE THREAD

**Issue by UltraBurstXD** [PacktPublishing/Django-3-Web-Development-Cookbook-Fourth-Edition#19]
Hi,
I'm running into some errors when I try to run chapter 2, on Ubuntu 20.10:
~~~ python
File "/home/[user_name]/DjangoProjects/ch03/myproject_virtualenv/src/django-myproject/myproject/apps/search/multilingual_whoosh_backend.py", line 31, in __init__
    lang_code_underscored = translation.get_language().replace("-", "_")
~~~

I simply don't know what's going on... Does Django changes so much on each newer release?

**Comment by archatas** [comment]
Hello, @UltraBurstXD!

It seems that you were testing Chapter 3, not Chapter 2, which I can see from your traceback path (`ch03`).

Indeed, there were some dependency errors, but unrelated to Whoosh backend and translations. The dependency errors happened because the book was started some months before the official launch of Django 3.0 and some third-party modules seemed to have some compatibility issues then.

Today I updated the pip requirements for Chapter 3. Please reinstall them to your virtual environment. If you still can't run the Django project, make sure that you have:

1. A virtual environment with Python 3.6 - 3.9.
2. PostgreSQL 10 database.
3. myproject/settings/secrets.json file with the credentials of your PostgreSQL database.
4. Elasticsearch 7.8.0 server. (I recommend using [evm](https://github.com/duydo/evm) to manage Elasticsearch servers).
5. You have executed management commands:
    - `python manage.py migrate --settings=myproject.settings.dev`
    - `python manage.py createsuperuser --settings=myproject.settings.dev`
    - `python manage.py runserver --settings=myproject.settings.dev`
6. You added some categories and ideas to the database.
7. You might have executed management commands:
    - `python manage.py rebuild_index --settings=myproject.settings.dev`
    - `python manage.py search_index --rebuild --settings=myproject.settings.dev`

If you get any other problems after this reply, let me know.
